version: '3'
services:
    nginx:
        image: nginx:1.19
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - ${DOCKER_HTTP_PORT:-80}:80
        links:
            - php
        networks:
            - app-net
    php:
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        links:
            - mysql
        networks:
            - app-net
        ports:
          - ${DOCKER_WS_PORT:-6001}:6001

    mysql:
        image: mysql:5.7
        ports:
            - ${DOCKER_DB_PORT:-3306}:3306
        environment:
            MYSQL_DATABASE: testing
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        command: mysqld --sql_mode=""
        volumes:  # Mount relative path source folder on host to absolute path destination folder on docker container
            - .docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        networks:
            - app-net

networks:
    app-net:
        driver: bridge

